version: 0.2

phases:
  pre_build:
    commands:
      - COMMIT_HASH=$(git rev-parse --short HEAD)
      - IMAGE_REPO_URI=${IMAGE_REPO_PREFIX}${IMAGE_REPO_NAME}
      - $(aws ecr get-login --no-include-email)
      - docker login --username $DOCKERHUB_USERNAME --password $DOCKERHUB_PASSWORD || true
  build:
    commands:
      - ${CODEBUILD_SRC_DIR}/get-env.sh docker_serverless_build
      - docker build ${CODEBUILD_SRC_DIR} --tag ${IMAGE_REPO_URI}:${COMMIT_HASH} --tag ${IMAGE_REPO_URI}:latest
  post_build:
    commands:
      - docker push ${IMAGE_REPO_URI}:${COMMIT_HASH}
      - docker push ${IMAGE_REPO_URI}:latest
