version: 0.2

batch:
  fast-fail: false
  build-list:
      - identifier: latest
        env:
          IMAGE_TAG: latest
          SERVERLESS_VERSION: 1.70.0
      - identifier: 2.13.0
        env:
          IMAGE_TAG: 2.13.0
          SERVERLESS_VERSION: 2.13.0

phases:
  pre_build:
    commands:
      - COMMIT_HASH=$(git rev-parse --short HEAD)
      - IMAGE_REPO_URI=${IMAGE_REPO_PREFIX}${IMAGE_REPO_NAME}
      - $(aws ecr get-login --no-include-email)
      - docker login --username $DOCKERHUB_USERNAME --password $DOCKERHUB_PASSWORD || true
  build:
    commands:
      - ${CODEBUILD_SRC_DIR}/get-env.sh docker_serverless_build
      - docker build --build-arg SERVERLESS_VERSION=${SERVERLESS_VERSION} ${CODEBUILD_SRC_DIR} --tag ${IMAGE_REPO_URI}:${COMMIT_HASH} --tag ${IMAGE_REPO_URI}:${IMAGE_TAG}
  post_build:
    commands:
      - docker push ${IMAGE_REPO_URI}:${COMMIT_HASH}
      - docker push ${IMAGE_REPO_URI}:${IMAGE_TAG}
