version: 0.2

phases:
  pre_build:
    commands:
      - COMMIT_HASH=$(git rev-parse --short HEAD)
      - IMAGE_REPO_URI=${IMAGE_REPO_PREFIX}${IMAGE_REPO_NAME}
      - docker login -u AWS -p $(aws ecr get-login-password) https://$(aws sts get-caller-identity --query 'Account' --output text).dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com || $(aws ecr get-login --no-include-email)
      - docker login --username $DOCKERHUB_USERNAME --password $DOCKERHUB_PASSWORD || true
  build:
    commands:
      - ${CODEBUILD_SRC_DIR}/get-env.sh docker_serverless_build
      - docker build --build-arg SERVERLESS_VERSION=2.13.0 ${CODEBUILD_SRC_DIR} --tag ${IMAGE_REPO_URI}:2.13.0
      - docker build --build-arg SERVERLESS_VERSION=3.34.0 ${CODEBUILD_SRC_DIR} --tag ${IMAGE_REPO_URI}:3.34.0 --tag ${IMAGE_REPO_URI}:latest
  post_build:
    commands:
      - docker push ${IMAGE_REPO_URI}:2.13.0
      - docker push ${IMAGE_REPO_URI}:3.34.0
      - docker push ${IMAGE_REPO_URI}:latest