version: 0.2

phases:
  pre_build:
    commands:
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - REPOSITORY_URI=173432075717.dkr.ecr.us-west-2.amazonaws.com/docker-serverless
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - ls -al ${CODEBUILD_SRC_DIR}
      - (cd ${CODEBUILD_SRC_DIR}; . ${CODEBUILD_SRC_DIR}/get-env.sh docker_serverless_build)
      - docker build -t $REPOSITORY_URI:latest ${CODEBUILD_SRC_DIR}
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
